### PR TITLE
Add "Dark Red"

### PR DESCRIPTION
**Pull request by igorsantos07**
Created by picking the green colors and moving Hue to `0` :)

Useful for "alert/danger" cards.

image

### CODE REVIEW

**Comment by awolkers** [comment]
Thank you for the suggestion. The color red though doesnt work well on dark grey backgrounds so I will not add this.

**Comment by igorsantos07** [comment]
Hmmm funny. It seems fine for me, but indeed it fails horribly in the WCAG test. What if I resubmit the PR with a lighter red / pinkish tone which passes the scenarios? One tone for UI elements and another for small text (if possible, or just the same lighter tone for all).

**Comment by igorsantos07** [comment]
Oh, awesome. You MADE a pink theme right before closing this, didn't even bother mentioning and just closed it straight away. Now I have just spent some time fiddling with WCAG just to try to create a PR and discover you sort of "had" the same idea.

Awesome open source work you're doing there. Thank you very much.

**Comment by awolkers** [comment]
Also fixed a lot of broken styling issues. After your pr I played around
with the red color but had no luck in getting a suitable one. Then came up
with the idea of adding a pink one.

Op zo 6 nov. 2022 18:40 schreef Igor Santos ***@***.***>:

**Pull request closed without merging**
